name: example
description: A new Flutter project.

publish_to: none
version: 1.0.0+2

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  adwaita: ^1.0.0
  desktop_multi_window:
    git:
      url: https://github.com/Kingtous/rustdesk_desktop_multi_window
  flutter:
    sdk: flutter
  libadwaita:
  libadwaita_window_manager:
  window_manager:

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis:

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
